# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

env:
    global:

        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - FOLDERNAME='linetools'
        - PYTHON_VERSION=3.6
        - CONDA_DEPENDENCIES='cython astropy sphinx scipy h5py pyyaml matplotlib'
        - PIP_DEPENDENCIES='cookiecutter gitpython'
        - EVENT_TYPE='pull_request push'
        - TASK='test'

    matrix:
      # Extra context is a way to override options that the user normally
      # specifies during the questions phase of the cookiecutter setup. The keys
      # being overridden here must exist in the cookiecutter.json
      # See https://cookiecutter.readthedocs.io/en/0.9.1/advanced_usage.html#injecting-extra-context
      - EXTRA_CONTEXT=''
      - EXTRA_CONTEXT='include_example_cython_code=y'
      - EXTRA_CONTEXT="package_name=AstropyProject" FOLDERNAME='AstropyProject'
      - EXTRA_CONTEXT='_parent_project=sunpy'
      - TASK='render' EXTRA_CONTEXT='include_example_cython_code=y initialize_git_repo=n'

install:

    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
   - cookiecutter --no-input ./ -o ../test $EXTRA_CONTEXT
   - cd ../test/$FOLDERNAME
   - if [[ $TASK == 'test' ]]; then python setup.py egg_info; fi
   - if [[ $TASK == 'test' ]]; then python setup.py build; fi
   - if [[ $TASK == 'test' ]]; then python setup.py build_docs; fi
   - if [[ $TASK == 'test' ]]; then python setup.py test; fi


after_success:
  - cd ../../package-template
  - bash .travis-deploy.sh
